//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFMI_Calculator
{
    using System;
    using System.Collections.Generic;
    
    public partial class userIdentity
    {
        public int Id { get; set; }
        public string userName { get; set; }
        public Nullable<int> userAge { get; set; }
        public Nullable<int> userHeight { get; set; }
        public Nullable<double> userWeight { get; set; }
        public Nullable<int> userBodyFat { get; set; }
    }
}
